### ISSUE TITLE
I can't use this with normal 1602 lcd 

### ISSUE THREAD

**Issue by Allinol-zz** [thibautrey/ArduinoScreenMessage#1]
Hello i'm trying to use this library for standard 1602 lcd without 74HC595 but i can't get it to work

**Comment by thibautrey** [comment]
I'm afraid you won't be able to use it without the 74HC595, unless you modify the library. It uses LiquidCrystalSPI so no luck without it.

**Comment by Allinol-zz** [comment]
Ok Thanks

2018-07-10 15:13 GMT+07:00 Thibaut Rey <notifications@github.com>:

**Comment by Allinol-zz** [comment]
You can close the Issue :)
